# Generated by Django 4.0.2 on 2022-02-24 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_profile_picture_profile_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name']},
        ),
    ]
